### PR TITLE
Upgrade library-go version

### PR DESCRIPTION
**Pull request by qJkee**
Bumping the library-go dependency to latest, this should take advantage of leader election changes for SNO clusters proposed in this [library-go PR](https://github.com/openshift/library-go/pull/1242) and performance improvements in this [PR](https://github.com/openshift/library-go/pull/1235).

* bump go version in builder image

### CODE REVIEW

**Comment by qJkee** [comment]
@sttts @tkashem could you please take a look?

**Review by sanchezl — CHANGES_REQUESTED** [review]
Update the go version in `go.mod` to `1.17` to match.

**Comment by qJkee** [comment]
Hi @sanchezl !
I've updated go version in `go.mod` file

**Review by sanchezl — APPROVED** [review]
/lgtm

**Pull request merged**
