### PR TITLE
Bug 1791145: 4.4 releases include kubernetes-kube-storage-version-migrator, which breaks 4.3->4.4 with: UpdatePayloadResourceTypeMissing: Could not update kubestorageversionmigrator "cluster" (125 of 515): the server does not recognize this resource, check extension A

### PR DESCRIPTION
**Pull request by sanchezl**
During an upgrade the resources one run-level at a time (vs all in parallel during install). 
During an upgrade an attempt is made to create an operator config CRD resource instance at run level 35, but the actual CRD resource manifest would not be applied until run-level 40.
This PR moves all related resource manifests to the same run-level.

### CODE REVIEW

**Comment by wking** [comment]
runlevel docs [here][1] (not sure if those are up to date), have no entry for 40.  This needs to come after the Kube API stuff in 10-29, and maybe after the core operators stuff in 60-69, right?

[1]: https://github.com/openshift/cluster-version-operator/blob/a45fa12c42047b24a70d8edaa17b85a7eaf6ad38/docs/dev/operators.md#how-do-i-get-added-as-a-special-run-level

**Comment by sanchezl** [comment]
> runlevel docs [here](https://github.com/openshift/cluster-version-operator/blob/a45fa12c42047b24a70d8edaa17b85a7eaf6ad38/docs/dev/operators.md#how-do-i-get-added-as-a-special-run-level) (not sure if those are up to date), have no entry for 40. This needs to come after the Kube API stuff in 10-29, and maybe after the core operators stuff in 60-69, right?

I opened issue https://github.com/openshift/cluster-kube-storage-version-migrator-operator/issues/10 to remind myself to review the run-levels used.

**Pull request merged**
